# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_客户端数据分析.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(412, 443)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.query_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.query_pushButton.setGeometry(QtCore.QRect(300, 140, 91, 41))
        self.query_pushButton.setObjectName("query_pushButton")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 277, 291))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 9, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox.setText("")
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 3, 2, 1, 1)
        self.xbgc_comboBox_2 = QtWidgets.QComboBox(self.layoutWidget)
        self.xbgc_comboBox_2.setObjectName("xbgc_comboBox_2")
        self.xbgc_comboBox_2.addItem("")
        self.gridLayout.addWidget(self.xbgc_comboBox_2, 7, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.device_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.device_comboBox.setObjectName("device_comboBox")
        self.device_comboBox.addItem("")
        self.device_comboBox.addItem("")
        self.device_comboBox.addItem("")
        self.device_comboBox.addItem("")
        self.device_comboBox.addItem("")
        self.device_comboBox.addItem("")
        self.gridLayout.addWidget(self.device_comboBox, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.show_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.show_comboBox.setObjectName("show_comboBox")
        self.show_comboBox.addItem("")
        self.show_comboBox.addItem("")
        self.show_comboBox.addItem("")
        self.show_comboBox.addItem("")
        self.show_comboBox.addItem("")
        self.gridLayout.addWidget(self.show_comboBox, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setEnabled(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.xbgc_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.xbgc_comboBox.setObjectName("xbgc_comboBox")
        self.xbgc_comboBox.addItem("")
        self.xbgc_comboBox.addItem("")
        self.gridLayout.addWidget(self.xbgc_comboBox, 6, 1, 1, 1)
        self.kssj_dateEdit = QtWidgets.QDateEdit(self.layoutWidget)
        self.kssj_dateEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.kssj_dateEdit.setAccelerated(True)
        self.kssj_dateEdit.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.kssj_dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2009, 1, 1), QtCore.QTime(0, 0, 0)))
        self.kssj_dateEdit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(1757, 9, 14), QtCore.QTime(0, 0, 0)))
        self.kssj_dateEdit.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.kssj_dateEdit.setCalendarPopup(True)
        self.kssj_dateEdit.setCurrentSectionIndex(0)
        self.kssj_dateEdit.setTimeSpec(QtCore.Qt.TimeZone)
        self.kssj_dateEdit.setDate(QtCore.QDate(2009, 1, 1))
        self.kssj_dateEdit.setObjectName("kssj_dateEdit")
        self.gridLayout.addWidget(self.kssj_dateEdit, 4, 1, 1, 1)
        self.jssj_dateEdit = QtWidgets.QDateEdit(self.layoutWidget)
        self.jssj_dateEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.jssj_dateEdit.setAccelerated(True)
        self.jssj_dateEdit.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.jssj_dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2009, 1, 1), QtCore.QTime(0, 0, 0)))
        self.jssj_dateEdit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(1757, 9, 14), QtCore.QTime(0, 0, 0)))
        self.jssj_dateEdit.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.jssj_dateEdit.setCalendarPopup(True)
        self.jssj_dateEdit.setTimeSpec(QtCore.Qt.TimeZone)
        self.jssj_dateEdit.setDate(QtCore.QDate(2009, 1, 1))
        self.jssj_dateEdit.setObjectName("jssj_dateEdit")
        self.gridLayout.addWidget(self.jssj_dateEdit, 5, 1, 1, 1)
        self.Att_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.Att_comboBox.setObjectName("Att_comboBox")
        self.Att_comboBox.addItem("")
        self.Att_comboBox.addItem("")
        self.Att_comboBox.addItem("")
        self.Att_comboBox.addItem("")
        self.gridLayout.addWidget(self.Att_comboBox, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 7, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.device_bh_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.device_bh_comboBox.setCurrentText("")
        self.device_bh_comboBox.setObjectName("device_bh_comboBox")
        self.gridLayout.addWidget(self.device_bh_comboBox, 3, 1, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 4, 2, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_3, 5, 2, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_4.setText("")
        self.checkBox_4.setChecked(True)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout.addWidget(self.checkBox_4, 6, 2, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 8, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 8, 0, 1, 1)
        self.checkBox_7 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_7.setText("")
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout.addWidget(self.checkBox_7, 8, 2, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 340, 251, 40))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.horizontalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_5 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_5.setObjectName("checkBox_5")
        self.verticalLayout.addWidget(self.checkBox_5)
        self.checkBox_6 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_6.setObjectName("checkBox_6")
        self.verticalLayout.addWidget(self.checkBox_6)
        self.query_pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.query_pushButton_2.setGeometry(QtCore.QRect(300, 210, 91, 41))
        self.query_pushButton_2.setObjectName("query_pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 412, 23))
        self.menubar.setObjectName("menubar")
        self.menuf = QtWidgets.QMenu(self.menubar)
        self.menuf.setObjectName("menuf")
        self.menu00 = QtWidgets.QMenu(self.menuf)
        self.menu00.setObjectName("menu00")
        self.menu11 = QtWidgets.QMenu(self.menuf)
        self.menu11.setObjectName("menu11")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action001 = QtWidgets.QAction(MainWindow)
        self.action001.setObjectName("action001")
        self.action002 = QtWidgets.QAction(MainWindow)
        self.action002.setObjectName("action002")
        self.action003 = QtWidgets.QAction(MainWindow)
        self.action003.setObjectName("action003")
        self.action111 = QtWidgets.QAction(MainWindow)
        self.action111.setObjectName("action111")
        self.action112 = QtWidgets.QAction(MainWindow)
        self.action112.setObjectName("action112")
        self.action113 = QtWidgets.QAction(MainWindow)
        self.action113.setObjectName("action113")
        self.menu00.addAction(self.action001)
        self.menu00.addAction(self.action002)
        self.menu00.addAction(self.action003)
        self.menu11.addAction(self.action111)
        self.menu11.addAction(self.action112)
        self.menu11.addAction(self.action113)
        self.menuf.addAction(self.menu00.menuAction())
        self.menuf.addAction(self.menu11.menuAction())
        self.menubar.addAction(self.menuf.menuAction())

        self.retranslateUi(MainWindow)
        self.device_comboBox.setCurrentIndex(1)
        self.show_comboBox.setCurrentIndex(0)
        self.Att_comboBox.setCurrentIndex(1)
        self.query_pushButton.clicked.connect(MainWindow.test)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "客户端数据分析"))
        self.query_pushButton.setText(_translate("MainWindow", "查看图形"))
        self.xbgc_comboBox_2.setCurrentText(_translate("MainWindow", "箱线图"))
        self.xbgc_comboBox_2.setItemText(0, _translate("MainWindow", "箱线图"))
        self.label_6.setText(_translate("MainWindow", "结束时间："))
        self.device_comboBox.setCurrentText(_translate("MainWindow", "芯棒烧结"))
        self.device_comboBox.setItemText(0, _translate("MainWindow", "芯棒沉积", "uuu"))
        self.device_comboBox.setItemText(1, _translate("MainWindow", "芯棒烧结"))
        self.device_comboBox.setItemText(2, _translate("MainWindow", "对接芯棒焊接"))
        self.device_comboBox.setItemText(3, _translate("MainWindow", "种棒焊接"))
        self.device_comboBox.setItemText(4, _translate("MainWindow", "合成棒沉积"))
        self.device_comboBox.setItemText(5, _translate("MainWindow", "合成棒烧结"))
        self.label_3.setText(_translate("MainWindow", "设备类型："))
        self.show_comboBox.setCurrentText(_translate("MainWindow", "周"))
        self.show_comboBox.setItemText(0, _translate("MainWindow", "周"))
        self.show_comboBox.setItemText(1, _translate("MainWindow", "月"))
        self.show_comboBox.setItemText(2, _translate("MainWindow", "芯棒"))
        self.show_comboBox.setItemText(3, _translate("MainWindow", "光棒"))
        self.show_comboBox.setItemText(4, _translate("MainWindow", "小盘光纤"))
        self.label.setText(_translate("MainWindow", "分析类型："))
        self.label_5.setText(_translate("MainWindow", "开始时间："))
        self.label_4.setText(_translate("MainWindow", "设备编号："))
        self.xbgc_comboBox.setCurrentText(_translate("MainWindow", "A151_2"))
        self.xbgc_comboBox.setItemText(0, _translate("MainWindow", "A151_2"))
        self.xbgc_comboBox.setItemText(1, _translate("MainWindow", "A151_1"))
        self.kssj_dateEdit.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.jssj_dateEdit.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.Att_comboBox.setCurrentText(_translate("MainWindow", "小盘1383"))
        self.Att_comboBox.setItemText(0, _translate("MainWindow", "小盘1310"))
        self.Att_comboBox.setItemText(1, _translate("MainWindow", "小盘1383"))
        self.Att_comboBox.setItemText(2, _translate("MainWindow", "小盘1550"))
        self.Att_comboBox.setItemText(3, _translate("MainWindow", "小盘截至波长"))
        self.label_8.setText(_translate("MainWindow", "图表类型："))
        self.label_7.setText(_translate("MainWindow", "芯棒工厂："))
        self.label_2.setText(_translate("MainWindow", "呈现方式："))
        self.label_9.setText(_translate("MainWindow", "单值查询："))
        self.checkBox_5.setText(_translate("MainWindow", "扣除异衰减变"))
        self.checkBox_6.setText(_translate("MainWindow", "扣除退棒"))
        self.query_pushButton_2.setText(_translate("MainWindow", "图形数据导出"))
        self.menuf.setTitle(_translate("MainWindow", "分析"))
        self.menu00.setTitle(_translate("MainWindow", "00"))
        self.menu11.setTitle(_translate("MainWindow", "11"))
        self.action001.setText(_translate("MainWindow", "001"))
        self.action002.setText(_translate("MainWindow", "002"))
        self.action003.setText(_translate("MainWindow", "003"))
        self.action111.setText(_translate("MainWindow", "111"))
        self.action112.setText(_translate("MainWindow", "112"))
        self.action113.setText(_translate("MainWindow", "113"))

